command_timeout = 1000

[directory]
truncation_length = 5
truncation_symbol = "../"
read_only = " ó°Œ¾"
style = "bold #0096FF"
repo_root_style = "bold #6699CC"
truncate_to_repo = false

[aws]
disabled = true

[status]
disabled = false

[fossil_branch]
symbol = "ï˜ "

[git_branch]
symbol = "ï˜ "
format = "[$symbol$branch(:$remote_branch)]($style) "

[lua]
format = '[$symbol $version ]($style)'
version_format = '${major}.${minor}'
symbol = " ğŸŒ™"


[nodejs]
format = '[$symbol $version ]($style)'
version_format = '${major}.${minor}'
symbol = " îœ˜"
style = "bold #FFA500"

[package]
disabled = true

[python]
format = '[$symbol $version (\($virtualenv\)) ]($style)'
version_format = '${major}.${minor}'
symbol = " ğŸ"
style = "bold #228b22"

[rust]
format = '[$symbol $version ]($style)'
version_format = '${major}.${minor}'
symbol = " ğŸ¦€"

[[battery.display]]
threshold = 30
style = 'bold red'

[cmd_duration]
disabled = true
